# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: {{ .Values.name }}-ingress
#   namespace: {{ $.Release.Namespace }}
#   labels:
#     app: {{ .Values.name }}-ingress


apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kong-ingress
  namespace: default
  annotations:
      konghq.com/strip-path: 'true'
  #    konghq.com/protocols: 'https'
spec:
  # ingressClassName: kong
  rules:
  - http:
      paths:
      - backend:
          service:
            name: nginx
            port:
              number: 80
        path: /nginx
        pathType: Prefix
  - http:
      paths:
      - backend:
          service:
            name: myapp-1
            port:
              number: 80
        path: /myapp
        pathType: Prefix
  - http:
      paths:
      - backend:
          service:
            name: svc-konga1
            port:
              number: 80
        path: /konga
        pathType: Prefix